### PR TITLE
Allow setting of shim

### PR DESCRIPTION
**Pull request by joedborg**

### CODE REVIEW

**Comment by Cynerva** [comment]
This looks like it might be fine, but it's hard to say without knowing how the shim config is used. How would I use this?

**Comment by joedborg** [comment]
Hey @Cynerva, it's in response to https://bugs.launchpad.net/charm-containerd/+bug/1827900

It's basically to adjust the `shim` config option in the containerd config file.

**Comment by Cynerva** [comment]
Ah, thanks. So this leaves it as the user's responsibility to install their custom shim (e.g. gvisor), yeah? Perhaps in some cases they could accomplish this by using the [layer-apt config options](https://github.com/stub42/layer-apt/blob/master/config.yaml), or in the less fortunate case, they might have to use `juju ssh` / `juju run` to do it. That's something we generally want to avoid, but I don't really see a way around it. So I'm good with that.

I do have another concern. Looking at gvisor as the provided example, they're not just setting a custom shim, but also a custom runtime: https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-quickstart.md. Are we perhaps not covering the whole story here?

**Comment by joedborg** [comment]
> I do have another concern. Looking at gvisor as the provided example, they're not just setting a custom shim, but also a custom runtime: https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-quickstart.md. Are we perhaps not covering the whole story here?

Thanks!  I had already done this but was going to make another PR.  Putting it here makes way more sense.

**Pull request merged**
