### PR TITLE
 LP1901050 Remove TLS files of old custom_registries

### PR DESCRIPTION
**Pull request by mfoliveira**
Upon config changes to the `custom_registries` option, any TLS files
of registries which are no longer in the new config are left behind.

So, check if `custom_registries` changed; if so remove the TLS files
of the old registries.  New registries have TLS files written anyway.
(If it has not changed, no files are removed.)

Note, this does not remove TLS files other than the previous config
(eg, left behind by older versions of the charm, or manually stored.)

Before:
```
	$ echo test >file

	$ juju config containerd custom_registries='[{"url": "registry-one", "ca_file": "'$(base64 <file)'", "key_file": "'$(base64 <file)'", "cert_file": "'$(base64 <file)'"}]'

	$ juju ssh containerd/0 'ls -1 /etc/containerd/'
	config.toml
	registry-one.ca
	registry-one.cert
	registry-one.key
	Connection to 10.191.59.168 closed.

	$ juju config containerd custom_registries='[{"url": "registry-two", "ca_file": "'$(base64 <file)'", "key_file": "'$(base64 <file)'", "cert_file": "'$(base64 <file)'"}]'

	$ juju ssh containerd/0 'ls -1 /etc/containerd/'
	config.toml
	registry-one.ca
	registry-one.cert
	registry-one.key
	registry-two.ca
	registry-two.cert
	registry-two.key
	Connection to 10.191.59.168 closed.
```

After:
```
	$ juju config containerd custom_registries='[{"url": "registry-three", "ca_file": "'$(base64 <file)'", "key_file": "'$(base64 <file)'", "cert_file": "'$(base64 <file)'"}]'

	$ juju ssh containerd/0 'ls -1 /etc/containerd/'
	config.toml
	registry-one.ca
	registry-one.cert
	registry-one.key
	registry-three.ca
	registry-three.cert
	registry-three.key
	Connection to 10.191.59.168 closed.
```

After; with no changes to "custom_registries" / pre-existing TLS files:
```
	$ juju config containerd no_proxy='custom_registries_not_changed.com'

	$ juju ssh containerd/0 'ls -1 /etc/containerd/'
	config.toml
	registry-one.ca
	registry-one.cert
	registry-one.key
	registry-three.ca
	registry-three.cert
	registry-three.key
	Connection to 10.191.59.168 closed.
```

Signed-off-by: Mauricio Faria de Oliveira <mfo@canonical.com>

### CODE REVIEW

**Comment by mfoliveira** [comment]
Please note only the second patch is for this PR, but it is on top of / needs the first patch / PR #45 due to `strip_url()` and context lines.
Sorry, I'm not sure how to reflect that appropriately in the PR interface.

**Comment by Cynerva** [comment]
Thanks. I've merged #45. Can you rebase from master to resolve conflicts?

**Comment by mfoliveira** [comment]
Thank you; just rebased and pushed it!

**Comment by Cynerva** [comment]
LGTM

**Pull request merged**
