### PR TITLE
`mirror` needed for custom registry

### PR DESCRIPTION
**Pull request by dmzoneill**
Please review this in relation to customer hotfix
SF#284415
https://canonical.my.salesforce.com/5003z0000293TcLAAU

### CODE REVIEW

**Comment by tvansteenburgh** [comment]
Thanks for the contribution. Can you please update the commit message to contain a description of the change?

**Comment by guoqiao** [comment]
> Thanks for the contribution. Can you please update the commit message to contain a description of the change?

Hi @tvansteenburgh,
thanks for the reminder about commit message, updated.
I was meant to try this to ensure it's working first and then create a formal PR.

**Comment by tvansteenburgh** [comment]
@joedborg Can you please file a bug in LP that we can link this too?

**Comment by joedborg** [comment]
https://bugs.launchpad.net/charm-containerd/+bug/1893649

**Comment by guoqiao** [comment]
hi joedborg, good point, I will make that change and re-push soon. thanks.

**Comment by guoqiao** [comment]
hi @joedborg:
The suggested change has been made, CI passed, new review appreciated.

**Pull request merged**
