### PR TITLE
Fix hook error during depart

### PR DESCRIPTION
**Pull request by Cynerva**
Fixes https://bugs.launchpad.net/charm-containerd/+bug/1867835

I haven't tested this at all, but seeing as this is holding up CI, maybe we can merge it in and test there.

### CODE REVIEW

**Comment by Cynerva** [comment]
Here's log output of the error that this PR is meant to fix:
```
unit-containerd-0: 12:59:45 DEBUG unit.containerd/0.containerd-relation-departed The following packages will be REMOVED:
unit-containerd-0: 12:59:45 DEBUG unit.containerd/0.containerd-relation-departed containerd*
unit-containerd-0: 12:59:45 DEBUG unit.containerd/0.containerd-relation-departed The following held packages will be changed:
unit-containerd-0: 12:59:45 DEBUG unit.containerd/0.containerd-relation-departed containerd
unit-containerd-0: 12:59:45 DEBUG unit.containerd/0.containerd-relation-departed 0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
unit-containerd-0: 12:59:45 DEBUG unit.containerd/0.containerd-relation-departed E: Held packages were changed and -y was used without --allow-change-held-packages.
unit-containerd-0: 12:59:45 ERROR unit.containerd/0.juju-log containerd:16: Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 74, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-containerd-0/charm/reactive/containerd.py", line 288, in purge_containerd
    apt_purge(CONTAINERD_PACKAGE, fatal=True)
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 326, in apt_purge
    _run_apt_command(cmd, fatal)
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 770, in _run_apt_co
    retry_message="Couldn't acquire DPKG lock")
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py", line 748, in _run_with_r
    result = subprocess.check_call(cmd, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', '--assume-yes', 'purge', 'containerd']' returned non-zero exit status 100.
unit-containerd-0: 12:59:45 ERROR juju.worker.uniter.operation hook "containerd-relation-departed" failed: exit status 1
```

**Comment by joedborg** [comment]
Have tested this with CK stable.  It's departing without error now; looks good to me.

**Comment by joedborg** [comment]
@kwmonroe do we not want the purge to hold the depart if there is an issue?

**Comment by Cynerva** [comment]
> my only question here would be whether or not we want fatal=True.

I would want to have it be non-fatal so we don't break things as bad in production. But if it was non-fatal, we wouldn't have caught this bug.

Either way, it was fatal=True before, I'm gonna leave it alone. Merging.

**Comment by kwmonroe** [comment]
@joedborg @Cynerva apologies for the ambiguity earlier.. when i questioned the `fatal=True`, i meant for the `apt_unhold` line (which defaults to `fatal=False`), not for the existing `apt_purge` line.

No biggie; I think it makes sense that we continue to consider `purge` fatal on failure.  If the unhold fails, we'll catch it on purge.

**Pull request merged**
